<div>
{include file="CRM/common/formButtons.tpl" location="top"}
</div>

<h3>This new form is generated by CRM/Civibooking/Form/Booking.php</h3>

{$form.favorite_color.label} {$form.favorite_color.html}

<div>
{include file="CRM/common/formButtons.tpl" location="bottom"}
</div>