<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.civicrm.booking/xml/schema/CRM/Booking/ResourceCriteria.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d33398fe12bdfd7066c63e29a16421ae)
 */
use CRM_Booking_ExtensionUtil as E;

/**
 * Database access object for the ResourceCriteria entity.
 */
class CRM_Booking_DAO_ResourceCriteria extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_booking_resource_criteria';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * @var int
   */
  public $id;

  /**
   * Foreign key to the resoure for this resource criteria.
   *
   * @var int
   */
  public $resource_id;

  /**
   * Foreign key to the resource criteria option group.
   *
   * @var string
   */
  public $criteria_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_booking_resource_criteria';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Resource Criterias') : E::ts('Resource Criteria');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'resource_id', 'civicrm_booking_resource', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'required' => TRUE,
          'where' => 'civicrm_booking_resource_criteria.id',
          'table_name' => 'civicrm_booking_resource_criteria',
          'entity' => 'ResourceCriteria',
          'bao' => 'CRM_Booking_DAO_ResourceCriteria',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'resource_id' => [
          'name' => 'resource_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Resource ID'),
          'description' => E::ts('Foreign key to the resoure for this resource criteria.'),
          'required' => TRUE,
          'where' => 'civicrm_booking_resource_criteria.resource_id',
          'table_name' => 'civicrm_booking_resource_criteria',
          'entity' => 'ResourceCriteria',
          'bao' => 'CRM_Booking_DAO_ResourceCriteria',
          'localizable' => 0,
          'FKClassName' => 'CRM_Booking_DAO_Resource',
          'add' => NULL,
        ],
        'criteria_id' => [
          'name' => 'criteria_id',
          'type' => CRM_Utils_Type::T_STRING,
          'description' => E::ts('Foreign key to the resource criteria option group.'),
          'required' => TRUE,
          'maxlength' => 512,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_booking_resource_criteria.criteria_id',
          'table_name' => 'civicrm_booking_resource_criteria',
          'entity' => 'ResourceCriteria',
          'bao' => 'CRM_Booking_DAO_ResourceCriteria',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'booking_resource_criteria', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'booking_resource_criteria', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
